import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getProducts, getProductByCollection, addToCart } from "../utils/shopify";
//import ProductCard from "../components/ProductCard/ProductCard";
import Landing from "../components/Landing"
// import Header from "../components/Header/Header";


export default function Home({ data, dataByCollection }) {
  const products = data.products.edges;

  return (
    <>
      <Head>
        <title>Nextjs Shopify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Landing products={products} collections={dataByCollection} />
        {/* <div className={styles.products}>
          {products.map((product) => {
            return <ProductCard key={product.node.id} product={product} />;
          })}
        </div> */}
        
  
      </main>
    </>
  );
}
export const getServerSideProps = async () => {
  
  const data = await getProducts();
 
  const dataByCollection = await getProductByCollection()
  return {
    props: { data, dataByCollection },
  };
};


